# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('mi_id', models.AutoField(primary_key=True, serialize=False)),
                ('inpr_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('mi_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('file_location', models.CharField(max_length=255)),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('mi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaas.MedicalImage')),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='PhysicianProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Tablespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, db_tablespace='indexes', max_length=30)),
                ('data', models.CharField(db_index=True, max_length=255)),
                ('edges', models.ManyToManyField(db_tablespace='indexes', related_name='_tablespace_edges_+', to='miaas.Tablespace')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField()),
                ('deactivate_date', models.DateField()),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='miaas.User')),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('physician_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='miaas.User')),
                ('field', models.CharField(max_length=30)),
                ('score', models.FloatField()),
                ('qualification', models.CharField(max_length=30)),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaas.User'),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaas.User'),
        ),
        migrations.AddField(
            model_name='physicianprofile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaas.Physician'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaas.Patient'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaas.Physician'),
        ),
    ]
