# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miaas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interpretation',
        ),
        migrations.RemoveField(
            model_name='medicalimage',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='mi_id',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='physician_id',
        ),
        migrations.RemoveField(
            model_name='physicianprofile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tablespace',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='MedicalImage',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='Physician',
        ),
        migrations.DeleteModel(
            name='PhysicianProfile',
        ),
        migrations.DeleteModel(
            name='Tablespace',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
